function jobResult = runProstateProtonMctRobustnessJob(varargin)
% runProstateProtonMctRobustnessJob Run prostate macro parameter sets in series.

% Path setup.
macroRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(macroRoot,'helpers'));

% Job execution defaults.
% profile: prod uses production defaults; testing applies explicit overrides.
% openGui: serial jobs usually run non-interactively.
profile = 'testing';
openGui = false;
stopOnError = true;

% Base MacroSpec selectors.
% Parameter sets below override robustness and sampling behavior.
base = struct();
base.label = 'prostate_1mct_protons';
base.site = 'prostate';
base.particleType = 'protons';
base.caseID = '1_mct';
base.samplingProfile = 'default';

% Job parameter sets.
% Each parameter set is merged over the base before execution.
parameterSets = repmat(struct( ...
    'label','', ...
    'robustness','', ...
    'samplingProfile','default', ...
    'optimizationScenario',struct(), ...
    'samplingScenario',struct()),1,3);

parameterSets(1).label = 'PTV';
parameterSets(1).robustness = 'PTV';
parameterSets(1).optimizationScenario = struct( ...
    'ctActive', true, ...
    'setupActive', true, ...
    'rangeActive', false, ...
    'gantryActive', false, ...
    'couchActive', false);
parameterSets(1).samplingScenario = struct( ...
    'ctActive', false, ...
    'setupActive', true, ...
    'rangeActive', false, ...
    'gantryActive', true, ...
    'couchActive', true);

parameterSets(2).label = 'COWC';
parameterSets(2).robustness = 'COWC';
parameterSets(2).optimizationScenario = struct( ...
    'ctActive', false, ...
    'setupActive', true, ...
    'rangeActive', true, ...
    'gantryActive', false, ...
    'couchActive', false);
parameterSets(2).samplingScenario = struct( ...
    'ctActive', false, ...
    'setupActive', true, ...
    'rangeActive', true, ...
    'gantryActive', true, ...
    'couchActive', true);

parameterSets(3).label = 'COWC_noAngles';
parameterSets(3).robustness = 'COWC';
parameterSets(3).samplingProfile = 'noAngles';
parameterSets(3).optimizationScenario = struct( ...
    'ctActive', false, ...
    'setupActive', true, ...
    'rangeActive', true, ...
    'gantryActive', false, ...
    'couchActive', false);
parameterSets(3).samplingScenario = struct( ...
    'ctActive', false, ...
    'setupActive', true, ...
    'rangeActive', true, ...
    'gantryActive', false, ...
    'couchActive', false);

% Resolve all parameter sets and run them in series.
job = struct();
job.id = 'prostate.protons.1_mct.robustness';
job.description = 'Prostate protons 1_mct robustness study.';
job.profile = profile;
job.openGui = openGui;
job.stopOnError = stopOnError;
job.base = base;
job.parameterSets = parameterSets;

jobResult = runWorkflowMacroJob(job,varargin{:});

end
