function result = runProstatePhotonMultipleWorkflow_wcScen(varargin)
% runProstatePhotonMultipleWorkflow_wcScen Run prostate multiple workflow with wcScen robust optimization.

% Path setup.
macroRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
addpath(fullfile(macroRoot,'helpers'));
specFolder = fullfile(macroRoot,'shared','specs');
if ~any(strcmp(strsplit(path,pathsep),specFolder))
    addpath(specFolder);
end
ensurePlanWorkflowAvailable('runProstatePhotonMultipleWorkflow_wcScen');

% Execution defaults.
profile = 'prod';
openGui = true;

% MacroSpec selectors.
site = 'prostate';
particleType = 'photons';
caseID = '3482';
robustness = 'multiple';
samplingProfile = 'default';

% Optimization scenario toggles.
optimizationScenario = struct( ...
    'ctActive', true, ...
    'setupActive', true, ...
    'rangeActive', false, ...
    'gantryActive', false, ...
    'couchActive', false);

% Sampling scenario remains the prostate macro default policy.
samplingScenario = struct( ...
    'ctActive', true, ...
    'setupActive', true, ...
    'rangeActive', false, ...
    'gantryActive', false, ...
    'couchActive', false);

specId = macroSpecId( ...
    site,particleType,caseID,robustness,samplingProfile);
[profile,args] = parseMacroProfileOption(profile,varargin{:});
spec = macroSpecCatalog(specId,'profile',profile);

robustPlans = planWorkflow.config.RobustPlanCatalog.select( ...
    spec.description,spec.planTemplate,spec.planKeys, ...
    'nominalScenario',spec.nominalScenario, ...
    'robustScenario',optimizationScenario, ...
    'radiationMode',spec.modality);

robustOptimizationScenario = optimizationScenario;
robustOptimizationScenario.mode = 'wcScen';
modifiedObjectiveSets = cell(1,0);
for planIx = 1:numel(robustPlans)
    objectiveSetName = char(robustPlans(planIx).objectiveSetName);
    if ~strcmp(objectiveSetName,'PTV')
        robustPlans(planIx).scenario = ...
            planWorkflow.config.ScenarioSpec.normalize( ...
            robustOptimizationScenario,robustPlans(planIx).scenario, ...
            sprintf('optimizationScenario.%s',objectiveSetName));
        modifiedObjectiveSets{end + 1} = objectiveSetName; %#ok<AGROW>
    end
end
if isempty(modifiedObjectiveSets)
    error('planWorkflow:macros:MissingFsVsDsRobustPlans', ...
        'Expected at least one non-PTV robust plan for FSvsDS.');
end

result = runWorkflowMacroSpec( ...
    specId,'profile',profile,'openGui',openGui, ...
    'optimizationScenario',optimizationScenario, ...
    'samplingScenario',samplingScenario, ...
    'allowCustomRobustPlans',true, ...
    'precompute',struct('robustPlans',robustPlans),args{:});
end
