% Batch execution script to evaluate different theta1 values
% for a given radiotherapy plan using matRad_processCDVH.
% Each theta1 value is injected into a base metadata structure.

% List of theta1 values to evaluate
theta1_values = [0.00, 0.01, 0.03, 0.07, 0.1, 0.3, 0.7, 1, 3, 7, 10];

% Base metadata definition (fixed parameters)
base_metadata = struct( ...
    'defaultRootPath', '/Volumes/Work_01/workspace/JOBS/Interval3', ...
    'jobPath', '', ...
    'job_folder', 'job1', ...
    'radiationMode', 'photons', ...
    'description', 'breast', ...
    'caseID', '3832', ...
    'robustness', 'INTERVAL3', ...
    'robustness_approach', 'robust', ...
    'plan_target', 'CTV', ...
    'plan_beams', '7F', ...
    'plan_objectives', '4', ...
    'shiftSD', '4x8x6', ...
    'scen_mode', 'impScen5', ...
    'wcFactor', 1.0, ...
    'kdin', 'dinamic', ...
    'kmax', 10, ...
    'retentionThreshold', 'k_10', ...
    'theta2', 1.0, ...
    'selected_folder', '2025-04-11 06-15-46' ...
);

% Loop through each theta1 value
for i = 1:numel(theta1_values)
    % Clone the base metadata
    metadata = base_metadata;
    
    % Update the current theta1 value
    metadata.theta1 = theta1_values(i);
    
    % Display progress in console
    fprintf('\n===========================\n');
    fprintf('Running for theta1 = %.2f\n', metadata.theta1);
    fprintf('===========================\n');
    
    % Run processing routine and catch errors to continue
    try
        matRad_processCDVH(metadata);
    catch ME
        warning('Failed for theta1 = %.2f: %s', metadata.theta1, ME.message);
    end
end
