metadata = struct( ...
    'defaultRootPath', '/Users/acsevillam/workspace/matRad/cminimax2', ...
    'jobPath', '', ...
    'job_folder', '', ...
    'radiationMode', 'photons', ...
    'description', 'prostate', ...
    'caseID', '3482', ...
    'robustness', 'INTERVAL3', ...
    'robustness_approach', 'robust', ...
    'plan_target', 'CTV', ...
    'plan_beams', '9F', ...
    'plan_objectives', '4', ...
    'shiftSD', '4x8x6', ...
    'scen_mode', 'impScen5', ...
    'wcFactor', 1.0, ...
    'theta1', 10.0, ...
    'kdin', 'dinamic', ...
    'kmax', 10, ...
    'retentionThreshold', 0.8, ...
    'theta2', 1.0 ...
);

matRad_processCDVH(metadata);

